language: rust
cache: cargo

install: cargo install rustsec-admin

# check that the advisory-db is well-formed
script: rustsec-admin lint

branches:
  only:
    - master

rust:
  - stable

notifications:
  irc: 'irc.mozilla.org#rustsec'
