language: rust
cache: cargo

install: cargo install rustsec-cli --git https://github.com/RustSec/rustsec-crate.git

# check that the advisory-db is well-formed
script: rustsec check

branches:
  only:
    - master

rust:
  - stable

notifications:
  irc: 'irc.mozilla.org#rustsec'
