[package]
name = "rustsec-advisory-db"
version = "0.0.0"
authors = ["Tony Arcieri <bascule@gmail.com>"]
repository = "https://github.com/rustsec/advisory-db"
documentation = "https://github.com/rustsec/advisory-db"
categories = ["api-bindings", "development-tools"]
keywords = ["rustsec", "security", "advisory", "vulnerability"]

[dependencies]
rustsec = "^0.2"
