[package]
name = "rustsec-advisory-db"
description = "Security advisory database for Rust crates published through crates.io"
version = "0.0.0"
authors = ["Tony Arcieri <bascule@gmail.com>"]
license_file = "LICENSE.txt"
repository = "https://github.com/rustsec/advisory-db"
documentation = "https://github.com/rustsec/advisory-db"
categories = ["api-bindings", "development-tools"]
keywords = ["rustsec", "security", "advisory", "vulnerability"]

[dependencies]
rustsec = "^0.2"
