[advisory]
id = "RUSTSEC-0000-0000"
package = "tiberius"
title = "tiberius is unmaintained"
informational = "unmaintained"
date = "2020-02-28" # last GitHub commit
url = "https://github.com/RustSec/advisory-db/issues/261"
description = """
The author of `tiberius` has archived the GitHub repository and left the
following note:

> I do not have the time to overhaul the library and do not intend to further
> maintain the 0.3 version relying on the old futures ecosystem.

Suggested alternatives are:

- [`odbc`](https://crates.io/crates/odbc)
- [`sqlx`](https://github.com/launchbadge/sqlx/issues/116) (forthcoming)
"""

[versions]
unaffected = ["> 0.3.2"] # last release
patched = []
