[advisory]
id = "RUSTSEC-2016-0006"
package = "cassandra"
title = "`cassandra` crate is unmaintained; use `cassandra-cpp` instead"
informational = "unmaintained"
date = "2016-12-15"
url = "https://github.com/tupshin/cassandra-rs/issues/52"
description = """
The `cassandra` crate has not seen a release since December 2016, and its author
is unresponsive.

The `cassandra-cpp` crate is a maintained fork:

https://github.com/Metaswitch/cassandra-rs
"""

[versions]
patched = []
unaffected = ["> 0.8.1"] # last release
