[advisory]
id = "RUSTSEC-2019-0032"
package = "crust"
title = "crust repo has been archived; use libp2p instead"
informational = "unmaintained"
date = "2019-11-21"
url = "https://github.com/maidsafe/crust"
description = """
** The `crust` crate repo was archived with no warning or explanation.**

Given that it was archived with no warning or successor, there's not an
official replacement but [`rust-libp2p`](https://github.com/libp2p/rust-libp2p)
looks like it's got a similar feature set and is actively maintained.
"""

[versions]
unaffected = ["> 0.32.1"] # last release
patched = []
