[advisory]
id = "RUSTSEC-2019-0021"
package = "linea"
date = "2019-09-14"
title = "`Matrix::zip_elements` causes double free"
url = "https://github.com/strake/linea.rs/issues/2"
categories = ["memory-corruption"]
keywords = ["double free"]
description = """
Affected versions of this crate did not properly implements the `Matrix::zip_elements` method, which causes an double free when the given trait implementation might panic.

This allows an attacker to corrupt or take control of the memory.
 
The flaw was corrected by Phosphorus15.
"""
aliases = ["CVE-2019-16880"]

[versions]
patched = ["> 0.9.4"]
