[advisory]
id = "RUSTSEC-2019-0031"
package = "spin"
title = "spin is no longer actively maintained"
informational = "unmaintained"
date = "2019-11-21"
url = "https://github.com/mvdnes/spin-rs/commit/7516c80"
unaffected_versions = ["> 0.5.2"] # last release
patched_versions = []
description = """
The author of the `spin` crate does not have time or interest to maintain it.

Consider [`lock_api`](https://crates.io/crates/lock_api) (a subproject of
`parking_lot`) as an alternative which also supports `no_std` environments.
"""
