[advisory]
id = "RUSTSEC-2020-0003"
package = "rust_sodium"
date = "2020-01-20"
informational = "unmaintained"
title = "rust_sodium is unmaintained; switch to a modern alternative"
description = """
The `rust_sodium` crate is no longer maintained by its current owner, who
advise in the repository readme that they are looking for
someone else to take ownership of it.

We recommend you switch to an alternative crate such as:
- [`sodiumoxide`](https://crates.io/crates/sodiumoxide)
"""
patched_versions = []
unaffected_versions = ["> 0.10.2"]
url = "https://github.com/maidsafe/rust_sodium/pull/117"
