[advisory]
id = "RUSTSEC-2019-0011"
package = "memoffset"
date = "2019-07-16"
title = "Flaw in offset_of and span_of causes SIGILL, potential memory unsafety"
description = """
Affected versions of this crate caused traps and/or memory unsafety by zero-initializing references.

The flaw was corrected by using `MaybeUninit`.
"""

patched_versions = [">= 0.5.0"]
unaffected_versions = ["< 0.3.0"]
url = "https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490"
