[advisory]
id = "RUSTSEC-2018-0011"
package = "arrayfire"
date = "2018-12-18"
title = "Enum repr causing potential memory corruption"
url = "https://github.com/arrayfire/arrayfire-rust/pull/177"
categories = ["memory-corruption"]
keywords = ["enum", "repr"]
description = """
The attribute repr() added to enums to be compatible with C-FFI caused
memory corruption on MSVC toolchain.

arrayfire crates <= version 3.5.0 do not have this issue when used with
Rust versions 1.27 or earlier. The issue only started to appear since
Rust version 1.28.

The issue seems to be interlinked with which version of Rust is being used.

The issue was fixed in crate 3.6.0.
"""
aliases = ["CVE-2018-20998"]

[versions]
patched = [">= 3.6.0"]
unaffected = ["<= 3.5.0"]

[affected]
arch = ["x86_64"]
os = ["windows"]
