[advisory]
id = "RUSTSEC-2018-0015"
package = "term"
title = "term is looking for a new maintainer"
informational = "unmaintained"
date = "2018-11-19"
url = "https://github.com/Stebalien/term/issues/93"
unaffected_versions = ["> 0.6.1"] # last release
patched_versions = []
description = """
The author of the `term` crate does not have time to maintain it and is looking
for a new maintainer.

Some maintained alternatives you can potentially switch to instead, depending
on your needs:

- [`crossterm`](https://github.com/crossterm-rs/crossterm)
- [`termcolor`](https://crates.io/crates/termcolor)
- [`yansi`](https://crates.io/crates/yansi)
"""
