[advisory]
id = "RUSTSEC-2016-0004"
package = "libusb"
title = "libusb is unmaintained; use rusb instead"
informational = "unmaintained"
date = "2016-09-10"
url = "https://github.com/dcuddeback/libusb-rs/issues/33"
description = """
The `libusb` crate has not seen a release since September 2016, and its author
is unresponsive.

The `rusb` crate is a maintained fork:

https://github.com/a1ien/rusb
"""

[versions]
patched = []
unaffected = ["> 0.3.0"] # last release
