[advisory]
id = "RUSTSEC-2020-0013"
package = "fake-static"
date = "2020-04-24"
title = "fake-static allows converting any reference into a `'static` reference"
description = """
fake-static allows converting a refernce with any lifetime into
a reference with `'static` lifetime without the `unsafe` keyword.

Internally, this crate does not use unsafe code, it instead
exploits a soundness bug in rustc:

https://github.com/rust-lang/rust/issues/25860
"""

[versions]
patched = []
