[advisory]
id = "RUSTSEC-2018-0012"
package = "orion"
date = "2018-12-20"
title = "Flaw in streaming state reset() functions can create incorrect results."
url = "https://github.com/brycx/orion/issues/46"
description = """
Affected versions of this crate did not properly reset a streaming state.

Resetting a streaming state, without finalising it first, creates incorrect results.
 
The flaw was corrected by not first checking if the state had already been reset, when calling reset().
"""
aliases = ["CVE-2018-20999"]

[versions]
patched = [">= 0.11.2"]
