[advisory]
id = "RUSTSEC-2020-0005"
package = "cbox"
date = "2020-03-19"
title = "CBox API allows to de-reference raw pointers without `unsafe` code"
url = "https://github.com/TomBebbington/cbox-rs/issues/2"
categories = ["memory-corruption"]
description = """
`CBox` and `CSemiBox` are part of the public API of the cbox crate
and they allow to create smart pointers from raw pointers and de-reference
them without the need of `unsafe` code.
"""

[versions]
patched = []
