[advisory]
id = "RUSTSEC-2018-0007"
package = "trust-dns-proto"
date = "2018-10-09"
title = "Stack overflow when parsing malicious DNS packet"
description = """
There's a stack overflow leading to a crash when Trust-DNS's parses a
malicious DNS packet.

Affected versions of this crate did not properly handle parsing of DNS message
compression (RFC1035 section 4.1.4). The parser could be tricked into infinite
loop when a compression offset pointed back to the same domain name to be
parsed.

This allows an attacker to craft a malicious DNS packet which when consumed
with Trust-DNS could cause stack overflow and crash the affected software.

The flaw was corrected by trust-dns-proto 0.4.3 and upcoming 0.5.0 release.
"""
patched_versions = [">= 0.4.3", ">= 0.5.0-alpha.3" ]
keywords = [ "stack-overflow", "crash" ]
