name: Validate

on:
  pull_request: {}
  push:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: rustsec-admin-v0.1.1

    - name: Install rustsec-admin
      run: cargo install rustsec-admin

    - name: Lint advisories
      run: rustsec-admin lint
