[advisory]
id = "RUSTSEC-2018-0010"
package = "openssl"
date = "2018-06-01"
title = "Use after free in CMS Signing"
url = "https://github.com/sfackler/rust-openssl/pull/942"
keywords = ["memory-corruption"]
description = "Affected versions of the OpenSSL crate used structures after they'd been freed."

[versions]
patched = [">= 0.10.9"]
unaffected = ["< 0.10.8"]
